name: CI

on:
  push:
    branches: [ main ]

jobs:
  generate:
    if : "!contains(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python and Dependancies
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
        python -mpip install qrcode[pil]
        python qrgenerator.py
